[package]
name = "searcher"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4 ", features = ["default", "cargo"] }
walkdir = { version = "2.5.0" }